### PR TITLE
Adding ingress dashboard to grafonnet

### PR DESCRIPTION
**Pull request by Manda-supraja26**
## Type of change

- [ ] Refactor
- [X] New feature
- [ ] Bug fix
- [X] Optimization
- [ ] Documentation Update

## Description
Adding ingress-performance dashboard  in grafonnet.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by krishvoor** [comment]
Hi @Manda-supraja26 👋 
While we review your first PR to cloud-bulldozer, it would lot easier for us to reference the panels and stuff from Grafana Report, can you share your Grafana Report link URL?

**Comment by Manda-supraja26** [comment]
Hello @krishvoor 👋, 
you can find the Grafana Report for the Ingress Performance at the following link: [Ingress-perf Grafana Report](https://grafana.rdu2.scalelab.redhat.com:3000/d/e70d57f4-057d-48f2-9738-61c3067345b5/ingress-dashboard-smanda?orgId=1)

**Comment by vishnuchalla** [comment]
> Hello @krishvoor 👋, you can find the Grafana Report for the Ingress Performance at the following link: [Ingress-perf Grafana Report](https://grafana.rdu2.scalelab.redhat.com:3000/d/e70d57f4-057d-48f2-9738-61c3067345b5/ingress-dashboard-smanda?orgId=1)

@rsevilla87 @krishvoor Any thoughts one these new visualizations?

**Comment by vishnuchalla** [comment]
@Manda-supraja26 I guess it needs rebase

**Comment by Manda-supraja26** [comment]
> @Manda-supraja26 I guess it needs rebase

@vishnuchalla sure,  i will do it

**Review by rsevilla87 — CHANGES_REQUESTED** [review]
Hey @Manda-supraja26, I recently added a couple of new panels to the original ingress-perf dashboard to track the CPU usage of some infrastructure components, could you add them??

image

**Comment by Manda-supraja26** [comment]
> Hey @Manda-supraja26, I recently added a couple of new panels to the original ingress-perf dashboard to track the CPU usage of some infrastructure components, could you add them?? thanks!
> 
> image

Hi  @rsevilla87, I will update the dashboard as requested. Thanks!

**Comment by Manda-supraja26** [comment]
current dashboard: [Ingress-Perf](https://grafana.rdu2.scalelab.redhat.com:3000/d/d6105ff8-bc26-4d64-951e-56da771b703d/ingress-perf?orgId=1)

Jsonnet coded dashboard: [Ingress-perf](https://grafana.rdu2.scalelab.redhat.com:3000/d/e70d57f4-057d-48f2-9738-61c3067345b5/ingress-dashboard-smanda?orgId=1)

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Pull request merged**
