### PR TITLE
Adding API-Performance-Overview Dashboard to grafonnet.

### PR DESCRIPTION
**Pull request by Manda-supraja26**
## Type of change

- [ ] Refactor
- [X] New feature
- [ ] Bug fix
- [X] Optimization
- [ ] Documentation Update

## Description

Adding API-Performance Dashboard to grafonnet

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by Manda-supraja26** [comment]
Current Dashboard: [Api-Performance dashboard](http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/MpfMxQKIz/api-performance?orgId=1&refresh=30s)

Jsonnet Coded Dashboard: [Api-perfromance dashboard](http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/B6BGbwFSk/api-performance-dashboard?orgId=1&refresh=30s)

**Comment by Manda-supraja26** [comment]
http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/MpfMxQKIz/api-performance?orgId=1&refresh=30s this is previous dashboard.

http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/B6BGbwFSk/api-performance-dashboard?orgId=1&refresh=30s this one is new one

**Comment by Manda-supraja26** [comment]
Hi @vishnuchalla 

old dashboard: http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/izpjYb5Ik/api-performance?orgId=1&refresh=30s

new dashboard: http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/7V2CLb5Sz/api-performance-dashboard?orgId=1&refresh=30s

**Comment by vishnuchalla** [comment]
label names and values doesn't seem to be matching exactly. Can you make sure that everything between the old and new dashboards is same.

Screenshot 2024-01-19 at 9 32 05 AM


Screenshot 2024-01-19 at 9 32 06 AM

**Review by vishnuchalla — CHANGES_REQUESTED** [review]
.

**Comment by afcollins** [comment]
Thanks for this PR @Manda-supraja26 ! I use this dashboard a lot and I would like the panel legends to have "Max" instead of "Last *".  That's a change I make in my own dashboard copies because "Current" doesn't give me the information I want.

Also, if the Tooltips can "sort descending" that is also more helpful when there are usually large numbers of data series in one panel.

**Comment by Manda-supraja26** [comment]
> Thanks for this PR @Manda-supraja26 ! I use this dashboard a lot and I would like the panel legends to have "Max" instead of "Last *". That's a change I make in my own dashboard copies because "Current" doesn't give me the information I want.
> 
> Also, if the Tooltips can "sort descending" that is also more helpful when there are usually large numbers of data series in one panel.

Thanks for the review @afcollins. i will work on suggested changes.

**Comment by Manda-supraja26** [comment]
@afcollins  i have updated the dashboard.  And dashboard link ARE:

> @vishnuchalla
> 
> old dashboard: http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/mniWpfpSk/api-performance?orgId=1&refresh=30s
> 
> new dashboard: http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/T6kZpftIk/api-performance-dashboard?orgId=1&refresh=30s

**Comment by vishnuchalla** [comment]
> @afcollins I have updated the dashboard. Please let me know if anything needs to be added. Dashboard links:
> 
> > @vishnuchalla
> > old dashboard: http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/mniWpfpSk/api-performance?orgId=1&refresh=30s
> > new dashboard: http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/T6kZpftIk/api-performance-dashboard?orgId=1&refresh=30s

@Manda-supraja26 I think its good to confirm that moving all the legends from "current" --> "max" is okay with all the users and is backward compatible.

**Comment by Manda-supraja26** [comment]
@vishnuchalla 
old dashboard: http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/Fxd0tZhIz/api-performance?orgId=1&refresh=30s

new dashboard: http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/_8OAtZ2Ik/api-performance-dashboard?orgId=1&refresh=30s

**Review by vishnuchalla — APPROVED** [review]
lgtm. Thanks :)

**Pull request merged**
