### PR TITLE
New Dashboard for hypershift components

### PR DESCRIPTION
**Pull request by mukrishn**
### Description
Included a new jsonnet template for populating hypershift dashboard with HostedControlPlane components.
Out - https://snapshots-origin.grafana.net/dashboard/snapshot/qAkJgcT651y4i2Ke5eeY6AIXKPJVbwM6?orgId=2

### CODE REVIEW

**Comment by mukrishn** [comment]
@rsevilla87 @dry923 PTAL

**Comment by dry923** [comment]
@mukrishn A couple of questions based on the dashboard snap that was linked. 

1) First, and potentially eliminating most other questions. Is this for a single hosted cluster or the entire management cluster? It is really not clear at a glance.
2) Is the OCP version referring to the hosted cluster(s) or the management cluster?
3) Can you add details around node counts?
4) Can you add a section surrounding API performance?

**Comment by mukrishn** [comment]
Thanks @dry923 
> 1. First, and potentially eliminating most other questions. Is this for a single hosted cluster or the entire management cluster? It is really not clear at a glance.

This is for monitoring all hosted clusters, `HostedClusterPlane Stats` panel would get repeated for each cluster, Idea is to monitor Hostedcluster only from this dashboard and all management  cluster status will be available in already existing template, but open for suggestion still WIP.

> 2. Is the OCP version referring to the hosted cluster(s) or the management cluster?

Good catch! I have included Management cluster version here. It should be hosted clusters, but that specific information is not available in exposed metrics yet. It might be available after this https://issues.redhat.com/browse/HOSTEDCP-293
> 3. Can you add details around node counts?

AFAIK, that metrics is not available yet, will double check.
> 4. Can you add a section surrounding API performance?

Only [these](https://docs.google.com/spreadsheets/d/1_98NadMOSYkfjc1DTo3KZXp_M6qaYsRFtiaYNc-yKlI/edit#gid=0) are available as of now, will check again and update if anything new added recently.

**Comment by smalleni** [comment]
LGTM - good start. We can iterate as we go forward.

**Review by dry923 — APPROVED** [review]
LGTM!

**Pull request merged**
