### PR TITLE
Remove jq's dependency

### LINKED ISSUE #38: Remove jq dependency for dittybopper deployment
Current implementation expects jq package to be installed on the host to deploy dittybopper: https://github.com/cloud-bulldozer/performance-dashboards/blob/master/dittybopper/k8s-deploy.sh#L110 which creates an additional dependency. Thoughts on removing the dependency?

### PR DESCRIPTION
**Pull request by krishvoor**
### Description
* Removes `jq` dependency
* updates README.md

### Fixes
#38

### CODE REVIEW

**Comment by krishvoor** [comment]
Hi @chaitanyaenr, @mukrishn - ptal

**Dittybopper**
Install Logs: http://pastebin.test.redhat.com/1070490
Uninstall Logs: http://pastebin.test.redhat.com/1070491

**Review by chaitanyaenr — APPROVED** [review]
LGTM!

**Review by jtaleric — APPROVED** [review]
lgtm

**Comment by krishvoor** [comment]
Rebased, @chaitanyaenr @jtaleric @mukrishn 
Ptal.

**Review by mukrishn — APPROVED** [review]
LGTM

**Pull request merged**
