### PR TITLE
Include assets in build requirements

### PR DESCRIPTION
**Pull request by rsevilla87**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

If any of the assets is modified, make should rebuild the templates-

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
lgtm. Thanks

**Review by vishnuchalla — APPROVED** [review]

**Comment by rsevilla87** [comment]
> @rsevilla87 I think at present, when something is modified in assets we already see those changes reflected. Did you come across any issues recently?

It doesn't track the changes as is now

```shell
rsevilla@wonderland ~/labs/performance-dashboards (master) $ make v2 
bin/jsonnetfmt -i templates/CPT/ingress-perf-v2.jsonnet templates/CPT/k8s-netperf-v2.jsonnet templates/CPT/kube-burner-report-mode-v2.jsonnet templates/CPT/kube-burner-report-ocp-wrapper-v2.jsonnet templates/General/api-performance-overview-v2.jsonnet templates/General/cilium-k8s-perf-v2.jsonnet templates/General/etcd-on-cluster-dashboard-v2.jsonnet templates/General/hypershift-performance-v2.jsonnet templates/General/k8s-perf-v2.jsonnet templates/General/ocp-performance-v2.jsonnet templates/General/ovn-monitoring-v2.jsonnet templates/General/pgbench-dashboard-v2.jsonnet templates/General/uperf-v2.jsonnet templates/General/vegeta-wrapper-v2.jsonnet templates/General/ycsb-v2.jsonnet
Rendered the v2 dashboards with latest grafonnet library
rsevilla@wonderland ~/labs/performance-dashboards (master) $ echo > assets/kube-burner-report-mode/panels.libsonnet 
rsevilla@wonderland ~/labs/performance-dashboards (master) $ make v2 
bin/jsonnetfmt -i templates/CPT/ingress-perf-v2.jsonnet templates/CPT/k8s-netperf-v2.jsonnet templates/CPT/kube-burner-report-mode-v2.jsonnet templates/CPT/kube-burner-report-ocp-wrapper-v2.jsonnet templates/General/api-performance-overview-v2.jsonnet templates/General/cilium-k8s-perf-v2.jsonnet templates/General/etcd-on-cluster-dashboard-v2.jsonnet templates/General/hypershift-performance-v2.jsonnet templates/General/k8s-perf-v2.jsonnet templates/General/ocp-performance-v2.jsonnet templates/General/ovn-monitoring-v2.jsonnet templates/General/pgbench-dashboard-v2.jsonnet templates/General/uperf-v2.jsonnet templates/General/vegeta-wrapper-v2.jsonnet templates/General/ycsb-v2.jsonnet
Rendered the v2 dashboards with latest grafonnet library

```

**Comment by vishnuchalla** [comment]
> > @rsevilla87 I think at present, when something is modified in assets we already see those changes reflected. Did you come across any issues recently?
> 
> It doesn't track the changes as is now
> 
> ```shell
> rsevilla@wonderland ~/labs/performance-dashboards (master) $ make v2 
> bin/jsonnetfmt -i templates/CPT/ingress-perf-v2.jsonnet templates/CPT/k8s-netperf-v2.jsonnet templates/CPT/kube-burner-report-mode-v2.jsonnet templates/CPT/kube-burner-report-ocp-wrapper-v2.jsonnet templates/General/api-performance-overview-v2.jsonnet templates/General/cilium-k8s-perf-v2.jsonnet templates/General/etcd-on-cluster-dashboard-v2.jsonnet templates/General/hypershift-performance-v2.jsonnet templates/General/k8s-perf-v2.jsonnet templates/General/ocp-performance-v2.jsonnet templates/General/ovn-monitoring-v2.jsonnet templates/General/pgbench-dashboard-v2.jsonnet templates/General/uperf-v2.jsonnet templates/General/vegeta-wrapper-v2.jsonnet templates/General/ycsb-v2.jsonnet
> Rendered the v2 dashboards with latest grafonnet library
> rsevilla@wonderland ~/labs/performance-dashboards (master) $ echo > assets/kube-burner-report-mode/panels.libsonnet 
> rsevilla@wonderland ~/labs/performance-dashboards (master) $ make v2 
> bin/jsonnetfmt -i templates/CPT/ingress-perf-v2.jsonnet templates/CPT/k8s-netperf-v2.jsonnet templates/CPT/kube-burner-report-mode-v2.jsonnet templates/CPT/kube-burner-report-ocp-wrapper-v2.jsonnet templates/General/api-performance-overview-v2.jsonnet templates/General/cilium-k8s-perf-v2.jsonnet templates/General/etcd-on-cluster-dashboard-v2.jsonnet templates/General/hypershift-performance-v2.jsonnet templates/General/k8s-perf-v2.jsonnet templates/General/ocp-performance-v2.jsonnet templates/General/ovn-monitoring-v2.jsonnet templates/General/pgbench-dashboard-v2.jsonnet templates/General/uperf-v2.jsonnet templates/General/vegeta-wrapper-v2.jsonnet templates/General/ycsb-v2.jsonnet
> Rendered the v2 dashboards with latest grafonnet library
> ```

Assets need not necessarily get rendered. They get compiled underneath and help generate the dashboard json for us. So they are being used underneath already if that is what your concern is.

**Comment by rsevilla87** [comment]
> > > @rsevilla87 I think at present, when something is modified in assets we already see those changes reflected. Did you come across any issues recently?
> > 
> > 
> > It doesn't track the changes as is now
> > ```shell
> > rsevilla@wonderland ~/labs/performance-dashboards (master) $ make v2 
> > bin/jsonnetfmt -i templates/CPT/ingress-perf-v2.jsonnet templates/CPT/k8s-netperf-v2.jsonnet templates/CPT/kube-burner-report-mode-v2.jsonnet templates/CPT/kube-burner-report-ocp-wrapper-v2.jsonnet templates/General/api-performance-overview-v2.jsonnet templates/General/cilium-k8s-perf-v2.jsonnet templates/General/etcd-on-cluster-dashboard-v2.jsonnet templates/General/hypershift-performance-v2.jsonnet templates/General/k8s-perf-v2.jsonnet templates/General/ocp-performance-v2.jsonnet templates/General/ovn-monitoring-v2.jsonnet templates/General/pgbench-dashboard-v2.jsonnet templates/General/uperf-v2.jsonnet templates/General/vegeta-wrapper-v2.jsonnet templates/General/ycsb-v2.jsonnet
> > Rendered the v2 dashboards with latest grafonnet library
> > rsevilla@wonderland ~/labs/performance-dashboards (master) $ echo > assets/kube-burner-report-mode/panels.libsonnet 
> > rsevilla@wonderland ~/labs/performance-dashboards (master) $ make v2 
> > bin/jsonnetfmt -i templates/CPT/ingress-perf-v2.jsonnet templates/CPT/k8s-netperf-v2.jsonnet templates/CPT/kube-burner-report-mode-v2.jsonnet templates/CPT/kube-burner-report-ocp-wrapper-v2.jsonnet templates/General/api-performance-overview-v2.jsonnet templates/General/cilium-k8s-perf-v2.jsonnet templates/General/etcd-on-cluster-dashboard-v2.jsonnet templates/General/hypershift-performance-v2.jsonnet templates/General/k8s-perf-v2.jsonnet templates/General/ocp-performance-v2.jsonnet templates/General/ovn-monitoring-v2.jsonnet templates/General/pgbench-dashboard-v2.jsonnet templates/General/uperf-v2.jsonnet templates/General/vegeta-wrapper-v2.jsonnet templates/General/ycsb-v2.jsonnet
> > Rendered the v2 dashboards with latest grafonnet library
> > ```
> 
> Assets need not necessarily get rendered. They get compiled underneath and help generate the dashboard json for us. So they are being used underneath already if that is what your concern is.

I know, but, as a requirement to generate the json dashboards, they should be a requirement, so once any of these assets is modified `make v2` will take action

**Pull request merged**
