### PR TITLE
Adding k8s Performance Dashboard to  grafonnet 

### PR DESCRIPTION
**Pull request by Manda-supraja26**
## Type of change

- [ ] Refactor
- [X] New feature
- [ ] Bug fix
- [X] Optimization
- [ ] Documentation Update

## Description

Adding k8s Performance Dashboard to  grafonnet.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
Requesting a link to the previous and current dashboards to make sure they are exactly the same look and feel wise.

**Review by vishnuchalla — CHANGES_REQUESTED** [review]
Requesting a link to the previous and current dashboards to make sure they are exactly the same look and feel wise.

**Comment by Manda-supraja26** [comment]
@vishnuchalla 

old dashboard:  http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/aLdAtW2Ik/k8s-performance?orgId=1&refresh=30s

new dashboard: http://dittybopper-dittybopper.apps.smanda-ocp1.perfscale.devcluster.openshift.com/d/1icAtWhSz/k8s-performance-dashboard?orgId=1&refresh=30s

**Review by vishnuchalla — APPROVED** [review]
lgtm

**Pull request merged**
