### PR TITLE
Add workload summary and compare data graphs on k8s-netperf

### PR DESCRIPTION
**Pull request by morenod**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Adding a new variable, compare by, to be used on the new graphs, to compare results by UUID, cluster Name, or OCP Version

image

Adding a table at the top with global information about the execution selected, like

image

Adding bar graphs for comparing results between one or more executions, with the information we provide on the result reports, like:

Node to Node
Pod to Pod
Pod to Pod via service

image

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by smalleni** [comment]
@jtaleric review please.

**Comment by jtaleric** [comment]
@morenod Awesome improvement!

**Review by jtaleric — APPROVED** [review]
lgtm, we just need to rebase w/ main before we merge.

**Comment by morenod** [comment]
@jtaleric rebased

**Review by rsevilla87 — APPROVED** [review]
I like the new panels,  lgtm!

**Pull request merged**
